-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public.autorzy
(
    id_autora serial NOT NULL,
    imie_autora character varying(30) COLLATE pg_catalog."default" NOT NULL,
    nazwisko_autora character varying(40) COLLATE pg_catalog."default",
    CONSTRAINT autorzy_pkey PRIMARY KEY (id_autora)
);

CREATE TABLE IF NOT EXISTS public.czytelnik
(
    id_czytelnika serial NOT NULL,
    imie character varying(30) COLLATE pg_catalog."default" NOT NULL,
    nazwisko character varying(30) COLLATE pg_catalog."default" NOT NULL,
    email character varying(40) COLLATE pg_catalog."default" NOT NULL,
    haslo character varying(30) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT czytelnik_pkey PRIMARY KEY (id_czytelnika),
    CONSTRAINT czytelnik_email_key UNIQUE (email)
);

CREATE TABLE IF NOT EXISTS public.ksiazka
(
    kod_ksiazki serial NOT NULL,
    tytul character varying(50) COLLATE pg_catalog."default" NOT NULL,
    id_autora integer NOT NULL,
    status character varying(25) COLLATE pg_catalog."default" NOT NULL,
    gatunek character varying(40) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT ksiazka_pkey PRIMARY KEY (kod_ksiazki)
);

CREATE TABLE IF NOT EXISTS public.wypozyczenia
(
    id_czytelnika integer NOT NULL,
    kod_ksiazki integer NOT NULL,
    data_wypozyczenia date NOT NULL,
    data_oddania date,
    CONSTRAINT wypozyczenia_pkey PRIMARY KEY (id_czytelnika, kod_ksiazki, data_wypozyczenia)
);

ALTER TABLE IF EXISTS public.ksiazka
    ADD CONSTRAINT ksiazka_fk FOREIGN KEY (id_autora)
    REFERENCES public.autorzy (id_autora) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.wypozyczenia
    ADD CONSTRAINT wypozyczenia_fk FOREIGN KEY (id_czytelnika)
    REFERENCES public.czytelnik (id_czytelnika) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;
CREATE INDEX IF NOT EXISTS idx_wypozyczenia_id_czytelnika
    ON public.wypozyczenia(id_czytelnika);


ALTER TABLE IF EXISTS public.wypozyczenia
    ADD CONSTRAINT wypozyczenia_fk1 FOREIGN KEY (kod_ksiazki)
    REFERENCES public.ksiazka (kod_ksiazki) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;

END;